---
title: "04-speed-acc-jepg-noise-age"
output: html_document
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.width=3, fig.height=3, fig.crop = F, fig.pos = "tb",
                      fig.path='figs/',echo=F, warning=F, cache=T, message=F, include =F,
                      sanitize = T)
```

```{r load libraries}
library(here); library(kableExtra); library(rogme); library(ggridges); library(ggrepel)
source(here::here("R/helper_functions/libraries_and_functions.R"))
source(here::here("R/helper_functions/ewma_helper_funs.R"))
```

```{r set data paths}
data_path <- "data/3_final_merged_data/first_shifts/"
ewma_path <- "data/3_final_merged_data/ewma_output/"
hddm_path <- "data/3_final_merged_data/hddm_output/"
```

```{r read first shift data}
d <- read_csv(here::here(data_path, "speed_acc_child_noise_fstshift_tidy.csv")) 
```

```{r read ewma}
files <- dir(path = ewma_path, pattern = "*.csv") 
d_ewma <- files %>% purrr::map_df(read_ewma, path = ewma_path)
```

```{r read hddm}
d_hddm <- read_csv(here::here(hddm_path, "hddm_tidy.csv"))
```

## Continous age analysis

Filter first shift data. 

```{r}
d_fst <- d %>% 
  filter(keep_runsheet %in% c("yes", "keep"), 
         keep_et == "include") %>% 
  filter(rt <= 1.5,
         response_onset_type == "noun",
         shift_start_location == "center") %>% 
  mutate(shift_acc_num = ifelse(shift_accuracy_clean == "correct", 1, 0),
         log_rt = log(rt))
```

Aggregate accuracy and RT.

```{r}
ss <- d_fst %>% 
  mutate(correct_num = ifelse(shift_accuracy == "correct", 1, 0)) %>% 
  group_by(subid, age) %>% 
  summarise(m_rt = median(rt),
            m_acc = mean(correct_num))
```

### Make developmental plots 

```{r set global plot values}
pt_size <- 3
pt_alpha <- 0.8
pt_shape <- 21
pt_width <- 0.15
pt_color <- "black"
pt_fill <- "darkgrey"
```

```{r make acc-age plot}
acc <- ss %>% 
  filter(m_acc > 0) %>% 
  ggplot(aes(x = age / 365, 
             y = m_acc)) +
  geom_point(shape = pt_shape, 
             color = pt_color, 
             size = pt_size,
             fill = pt_fill,
             alpha = pt_alpha) +
  geom_smooth(method = "lm", se = T) +
  geom_hline(yintercept = 0.5, linetype = "dashed") +
  labs(x = "Child's age (days)", y = "Prop. Correct") +
  lims(y = c(0, 1)) +
  theme(strip.text = element_text(size = 18),
        axis.text = element_text(size = 16),
        axis.title = element_text(size = 16))
```

```{r}
rt <- ss %>% 
  ggplot(aes(x = age / 365, 
             y = m_rt)) +
  geom_smooth(method = "lm", se = T) +
  geom_point(shape = pt_shape, 
             color = pt_color, 
             size = pt_size,
             fill = pt_fill,
             alpha = pt_alpha) +
  labs(x = "Child's age (days)", y = "Mean RT (sec)") +
  lims(y = c(0, 1.2)) +
  theme(strip.text = element_text(size = 18),
        axis.text = element_text(size = 16),
        axis.title = element_text(size = 16))
```

```{r}
cowplot::plot_grid(rt, acc)
```

### EWMA 

```{r}
d_ewma_kids <- d_ewma %>% filter(experiment %in% c("noise", "noise_gaze"), 
                   age_code == "child") %>% 
  mutate(condition = ifelse(str_detect(condition, pattern = "noise"), 
                            "noise", 
                            "clear")) 
```

```{r}
d_ewma_kids %<>% 
  mutate(gaze_condition = ifelse(str_detect(condition, "gaze"), "gaze", 
                                 "straight_ahead"),
         noise_condition = ifelse(str_detect(condition, "noise"), "noise", "clear")) %>%
  filter(gaze_condition == "straight_ahead", rt <= 2) %>% 
  group_by(subid, age_code, guess) %>% 
  summarise(count = n()) %>% 
  mutate(prop.responding = round(count / sum(count), 2)) %>% 
  filter(guess == "response") 
```

```{r}
ages <- d %>% 
  select(age, subid_short) %>% 
  rename(subid = subid_short) %>% 
  mutate(subid = as.character(subid))

ss_ewma <- d_ewma_kids %>% left_join(ages) %>% distinct()
```

Make the plot

```{r}
ss_ewma %>% 
  ggplot(aes(x = age / 365, 
             y = 1 - prop.responding)) +
  geom_smooth(method = "lm", se = T) +
  geom_point(shape = pt_shape, 
             color = pt_color, 
             size = pt_size,
             fill = pt_fill,
             alpha = pt_alpha) +
  labs(x = "Child's age (days)", y = "Prop. Language-Driven") +
  lims(y = c(0., 0.9)) +
  theme(strip.text = element_text(size = 18),
        axis.text = element_text(size = 16),
        axis.title = element_text(size = 16))
```







### HDDM 

