---
title: "Speed-Acc Visualize EWMA"
author: "Kyle MacDonald"
output: html_document
---

```{r setup, include=FALSE}
rm(list=ls())
knitr::opts_chunk$set(echo=F, warning=F, cache=F, message=F, sanitize = T)
source("../../helper_functions/libraries_and_functions.R")
source("../../helper_functions/ewma_helper_funs.R")
```

```{r}
ewma.path <- "../../../data/3_final_merged_data/ewma_output/"
plot.save.path <- "../../../paper/figs/"
```

## Read data

```{r read data}
files <- dir(path = ewma.path, pattern = "*.csv") 

# read in all files using purrr
d <- files %>% purrr::map_df(read_ewma, path = ewma.path)
```

## Visualize EWMA results: boxplots 

```{r make_text_boxplot}
ss.responding.prop <- d %>% 
  filter(experiment == "text") %>% 
  group_by(subid, condition, guess) %>% 
  summarise(count = n()) %>% 
  mutate(prop.responding = round(count / sum(count), 2))

ss.responding.prop %>% 
  filter(condition != "ASL", guess == "response") %>% 
  ggplot(aes(x = fct_rev(condition), y = prop.responding)) +
  geom_boxplot(fill = "dodgerblue", width = 0.3, alpha = 0.9) +
  labs(x = "Condition",y = "Prop. Shifts Language Driven") +
  theme(text = element_text(size = 12))
```

## Visualize EWMA results: control charts

### Text experiment (adults)

```{r make_text_ewma_plot}
text_model_vals <- d %>% 
  filter(experiment == "text", rt <= 0.9) %>% 
  aggregate_ewma()

text_control_chart <- plot_ewma_chart(text_model_vals)
text_control_chart
```

Save control chart.

```{r}
ggsave(plot = text_control_chart, 
       filename = paste0(plot.save.path, "e2_control_chart.png"), 
       width = 3, height = 3.5)
```

### Noise/Gaze experiment (adults)

```{r make_text_ewma_plot}
ng_model_vals <- d %>% 
  filter(experiment == "noise_gaze", rt <= 0.9) %>% 
  aggregate_ewma()

ng_control_chart <- plot_ewma_chart(ng_model_vals)
ng_control_chart
```

Save control chart.

```{r}
ggsave(plot = ng_control_chart, 
       filename = paste0(plot.save.path, "adult_ng_control_chart.png"), 
       width = 3, height = 3.5)
```

### Trio experiment (kids)

```{r}
trio_model_vals <- d %>% 
  filter(experiment == "trio", age_code != "adult", 
         rt <= 1.5) %>%
  mutate(condition = forcats::fct_relevel(condition, "ASL", "Face", "Object", "Bullseye")) %>% 
  aggregate_ewma()

trio_control_chart <- plot_ewma_chart(trio_model_vals)
trio_control_chart
```

Save control chart.

```{r}
ggsave(plot = trio_control_chart, 
       filename = paste0(plot.save.path, "e1_control_chart.png"), 
       width = 3, height = 3.5)
```

### Noise experiment (kids)

```{r}
noise_model_vals <- d %>% 
  filter(experiment == "noise", age_code != "adult", 
         rt <= 1.5) %>% 
  aggregate_ewma()
```

```{r}
noise_control_chart <- plot_ewma_chart(noise_model_vals)
noise_control_chart
```

### Gaze experiment (kids)

```{r}
gaze_model_vals <- d %>% 
  filter(experiment == "gaze", age_code != "adult", 
         rt <= 1.5) %>% 
  aggregate_ewma()
```

```{r}
gaze_control_chart <- plot_ewma_chart(gaze_model_vals)
gaze_control_chart
```