---
title: "Speed-Acc Statistical Models"
output: html_document
---

## Setup

```{r set global_options, include=FALSE}
library(here)
source(here::here("R/helper_functions/libraries_and_functions.R"))
data_path <- "data/3_final_merged_data/first_shifts/"
```

```{r read data}
d_kids_noise <- read_csv(here::here(data_path, "speed_acc_child_noise_fstshift_tidy.csv")) 
d_kids_gaze <- read_csv(here::here(data_path, "speed_acc_child_gaze_fstshift_tidy.csv")) 
d_adults <- read_csv(here::here(data_path, "speed_acc_adult_ng_fstshift_tidy.csv")) 
```

## Merge datasets

```{r clean datasets for merge}
d_adults %<>% select(-age)

d_kids_noise %<>% mutate(gaze_condition = ifelse(gaze_condition == "no_gaze", 
                                                 "straight_ahead", 
                                                 gaze_condition))

d_kids_gaze %<>% mutate(noise_condition = ifelse(noise_condition == "no_noise", 
                                                 "clear", 
                                                 noise_condition))
```

```{r merge datasets}
d <- bind_rows(mutate(d_kids_noise, experiment = "kids_noise", age_category = "children"),
               mutate(d_kids_gaze, experiment = "kids_gaze", age_category = "children"),
               mutate(d_adults, experiment = "adults_ng", age_category = "adults")) %>% 
  select(-resp_onset_type_fact, -subid_short) %>% 
  mutate(age_category = factor(age_category) %>% fct_rev()) 

# uncomment below to test that we have the right number of rows after the merge (result should be TRUE)
# nrow(d_kids_gaze) + nrow(d_kids_noise) + nrow(d_adults) == nrow(d)
```


## Noise experiment (Rt and Accuracy models)

```{r e1_filter}
d_e1_analysis <- d %>% 
  filter(experiment != "kids_gaze",
         keep_runsheet %in% c("yes", "keep"), 
         keep_et == "include",
         gaze_condition == "straight_ahead") %>% 
  filter(rt <= 1.5,
         response_onset_type == "noun", 
         shift_start_location == "center") %>% 
  mutate(shift_acc_num = ifelse(shift_accuracy_clean == "correct", 1, 0),
         log_rt = log(rt))
```


```{r e1 glmms}
m_bglm_acc_e1 <- stan_glmer(
  shift_acc_num ~ noise_condition + age_category + (noise_condition + target_image | subid), 
  data = d_e1_analysis,
  family = binomial(link = "logit"), 
  prior = normal(0, 2),
  prior_intercept = normal(0, 1),
  prior_covariance = decov(regularization = 2), # prior on Covariance matrices for mixed effects model
  chains = 4
)

m_bglm_rt_e1 <- stan_glmer(
  log_rt ~ noise_condition + age_category + (noise_condition + target_image | subid), 
  family = gaussian(),
  data = d_e1_analysis,
  prior = normal(0, 2), 
  prior_intercept = normal(0, 5),
  prior_covariance = decov(regularization = 2), # prior on Covariance matrices for mixed effects model
  chains = 4
)

beepr::beep(sound = 3)
```

```{r e1 extract posterior samples}
# get posterior samples
samples_e1_acc <- m_bglm_acc_e1 %>% 
  as.data.frame() %>% 
  as_tibble() %>% 
  dplyr::rename(clear_children = `(Intercept)`,
                noise_beta = noise_conditionnoise,
                age_beta = age_categoryadults) %>% 
  select(clear_children, noise_beta, age_beta)

samples_e1_rt <- m_bglm_rt_e1 %>% 
  as.data.frame() %>% 
  as_tibble() %>% 
  dplyr::rename(clear_children = `(Intercept)`,
                noise_beta = noise_conditionnoise,
                age_beta = age_categoryadults) %>% 
  select(clear_children, noise_beta, age_beta)

# tidy up accuracy
samples_e1_acc_tidy <- samples_e1_acc %>% 
  mutate(noise_children = clear_children + noise_beta,
         clear_adults = clear_children + age_beta, 
         noise_adults = clear_children + noise_beta + age_beta,
         sample_id = 1:n()) %>% 
  gather(key = condition, value = param_est, -sample_id, -noise_beta, -age_beta) %>% 
  mutate(acc_prob_scale = logit_to_prob(param_est)) %>% 
  separate(condition, into = c("noise_condition", "age_category"))

# tidy up rt samples
samples_e1_rt_tidy <- samples_e1_rt %>% 
  mutate(noise_children = clear_children + noise_beta,
         clear_adults = clear_children + age_beta, 
         noise_adults = clear_children + noise_beta + age_beta,
         sample_id = 1:n()) %>% 
  gather(key = condition, value = param_est, -sample_id, -noise_beta, -age_beta) %>% 
  mutate(rt_ms_scale = exp(param_est)) %>% 
  separate(condition, into = c("noise_condition", "age_category")) 
```

Save the posterior samples for later analysis and visualization.

```{r}
posteriors <- list(rt_noise = samples_e1_rt_tidy,
                   acc_noise = samples_e1_acc_tidy)

saveRDS(posteriors, file = here::here("data/3_final_merged_data/first_shifts", "speed-acc-posterior-samples.rds"))
```

