---
title: "HDDM cleaning and merging"
output: html_document
---

```{r global_options, include=FALSE}
library(here); library(kableExtra)
source(here::here("R/helper_functions/libraries_and_functions.R"))
source(here::here("R/helper_functions/ewma_helper_funs.R"))
```

```{r data path}
hddm_path <- "data/3_final_merged_data/hddm_output/"
```

Get list of hddm files that are the output of 

```{r}
hddm_files <- list.files(here::here(hddm_path), pattern = "samples")
```


```{r}
conds <- c("ASL", "Face", "bull", "face", "text-no-audio", "text",
                    "straight_ahead_clear", "straight_ahead_noise", "gaze_clear",
                    "gaze_noise", "asl", "clear", "straightahead", "face", "gaze", "noise")


tidy_hddm <- function(file_name, condition_list) {
  
  d <- read_tsv(here::here(hddm_path, file_name))
  
  d_tidy <- d %>% 
  rename(sample_id = X1) %>% 
  gather(key = parameter, value = param_value, -sample_id, -experiment, -age_code)
  
  d_tidy %>% 
  mutate(condition = str_extract(string = parameter, 
                                 pattern = paste(condition_list, collapse = '|')),
         param_name = ifelse(str_detect(string = parameter, pattern = "a\\("), 
                             "boundary", 
                             "drift"))
  
}
```

```{r}
d_tidy <- hddm_files %>% purrr::map_df(tidy_hddm, condition_list = conds)
```

Write to disk.

```{r}
write_csv(d_tidy, here::here("data/3_final_merged_data/hddm_output/hddm_tidy.csv"))
```

