---
title: "speed-acc-tables"
author: "Kyle MacDonald"
date: "2/13/2018"
output: html_document
---

### EWMA Noise

```{r ewma results table, results="asis", include = F, eval = F}
ewma_table <- bind_rows(ms_cond_diff_cuts, ms_cond_diff_guessing) %>% 
  select(-Exp.)

ewma_table$Parameter[2] <- ""
ewma_table$Parameter[4] <- ""

ewma_table <- xtable::xtable(ewma_table, 
                             caption = "EWMA results. The guessing parameter refers to the proportion of gaze shifts classified as random vs. language-driven with higher values indicating more random responding. Estimate refers to the difference between condition or age group.",
                             align = "lllr")

xtable::print.xtable(ewma_table, type="latex", comment = F, table.placement = "t",
      floating.environment = "table", 
      include.rownames=FALSE)
```


### HDDM Noise

```{r hddm results}
hddm_table_age <- d_hddm %>% 
  filter(experiment %in% c("noise_gaze", "noise"),
         condition %in% c("straight_ahead_noise", "straight_ahead_clear",
                          "clear", "noise")) %>%
  mutate(condition = ifelse(str_detect(condition, "noise"), "noise", "clear"),
        age_code = ifelse(str_detect(age_code, "kid"), "children", "adults")) %>% 
  group_by(param_name, age_code) %>% 
  summarise(MAP = mean(param_value),
            HDI_lower = quantile(param_value, probs = 0.025),
            HDI_upper = quantile(param_value, probs = 0.975)) %>% 
  mutate_at(vars(MAP, HDI_lower, HDI_upper), round, digits = 2)


hddm_table_contrast <- d_hddm %>% 
  filter(experiment %in% c("noise_gaze", "noise"),
         condition %in% c("straight_ahead_noise", "straight_ahead_clear",
                          "clear", "noise")) %>%
  mutate(condition = ifelse(str_detect(condition, "noise"), "noise", "clear"),
        age_code = ifelse(str_detect(age_code, "kid"), "children", "adults")) %>% 
  filter(param_name == "boundary", age_code == "children") %>% 
  group_by(condition) %>% 
  mutate(sample_id = 1:n()) %>% 
  select(param_value, condition, sample_id) %>% 
  tidyr::spread(condition, param_value) %>%
  mutate(cond_diff = noise - clear) %>% 
  summarise(MAP = mean(cond_diff),
            HDI_lower = quantile(cond_diff, probs = 0.025),
            HDI_upper = quantile(cond_diff, probs = 0.975)) %>% 
  mutate_at(vars(MAP, HDI_lower, HDI_upper), round, digits = 2)
```

```{r print hddm table, include = F, results = "asis", eval = F}
hddm_table <- d_hddm %>% 
  filter(experiment %in% c("noise_gaze", "noise"),
         condition %in% c("straight_ahead_noise", "straight_ahead_clear",
                          "clear", "noise")) %>%
  mutate(Condition = ifelse(str_detect(condition, "noise"), "noise", "clear"),
         `Age Group` = ifelse(str_detect(age_code, "kid"), "children", "adults")) %>% 
  group_by(param_name, Condition, `Age Group`) %>% 
  summarise(MAP = mean(param_value),
            HDI_lower = quantile(param_value, probs = 0.025),
            HDI_upper = quantile(param_value, probs = 0.975)) %>% 
  rename(Parameter = param_name) %>% 
  mutate_at(vars(MAP, HDI_lower, HDI_upper), round, digits = 2) %>% 
  mutate_all(as.character) %>% 
  mutate(`Estimate [95% HDI]` = paste0(MAP, " [", HDI_lower, ", ", HDI_upper, "]")) %>% 
  select(-MAP, -HDI_lower, -HDI_upper)

# remove double entries in the table
hddm_table$Parameter[1] <- ""
hddm_table$Parameter[3] <- ""
hddm_table$Parameter[4] <- ""

hddm_table$Parameter[5] <- ""
hddm_table$Parameter[7] <- ""
hddm_table$Parameter[8] <- ""

# conditions
hddm_table$Condition[2] <- ""
hddm_table$Condition[4] <- ""
hddm_table$Condition[6] <- ""
hddm_table$Condition[8] <- ""

# now make the xtable
hddm_table <- xtable::xtable(hddm_table, 
                             caption = "HDDM parameter estimates for each age group and noise condition. The drift rate parameter indexes processing efficiency and the boundary separation parameter indexes participants' information accumulation threshold.",
                             align = "llllr")

hlines <- c(-1, 0, 4, nrow(hddm_table))

xtable::print.xtable(hddm_table, type="latex", comment = F, table.placement = "t",
      hline.after = hlines,
      floating.environment = "table", 
      include.rownames=FALSE)
```
